Checksums
awslabs/aws-c-s3 pull request #117
Opened 2021-04-22 16:15 UTC by ilevyor

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-04-22 16:36 UTC, justinboswell requested changes

2021-04-22 16:36 UTC, justinboswell commented on .gitignore
> +!.vscode/extensions.json
Remove these exceptions. NOTHING from .vscode should ever be committed.

2021-04-22 16:36 UTC, justinboswell commented on include/aws/s3/aws_streaming_checksum.h
> +struct aws_checksum *aws_sha256_new(struct aws_allocator *allocator);
Just for completeness and good IDE integration results, go ahead and add:
```c
struct aws_checksum;
```

2021-04-22 16:36 UTC, justinboswell commented on include/aws/s3/aws_streaming_checksum.h
> +int aws_checksum_update(struct aws_checksum *checksum, const struct aws_byte_cursor *to_checksum);
`to_checksum` should just be `data` or `buffer` or `or similar

2021-04-22 16:36 UTC, justinboswell commented on include/aws/s3/aws_streaming_checksum.h
> +    Md5,
These should be caps, and prefix, e.g. `AWS_CHECKSUM_MD5`

2021-04-22 16:36 UTC, justinboswell commented on include/aws/s3/aws_streaming_checksum.h
> +int aws_md5_compute(
This should be `aws_checksum_md5_compute`

2021-04-22 16:36 UTC, justinboswell commented on include/aws/s3/aws_streaming_checksum.h
> +int aws_sha256_compute(
`aws_checksum_sha256_compute`

2021-04-22 16:36 UTC, justinboswell commented on include/aws/s3/aws_streaming_checksum.h
> +int aws_sha1_compute(
`aws_checksum_sha1_compute`

2021-04-28 15:29 UTC, justinboswell reviewed
Go ahead and knock out the SHA-1 stuff, and this is good to go

2021-04-28 15:29 UTC, justinboswell commented on include/aws/s3/s3_streaming_checksum.h
> +#define AWS_CRC_LEN 4
If these aren't needed/used, go ahead and delete them

2021-04-28 15:29 UTC, justinboswell commented on include/aws/s3/s3_streaming_checksum.h
> +typedef struct aws_checksum *(aws_checksum_new_fn)(struct aws_allocator *allocator);
This is an implementation detail, doesn't need to be in the public header.

2021-04-28 15:29 UTC, justinboswell commented on include/aws/s3/s3_streaming_checksum.h
> +*/
Don't check in commented out code, add this back when you add SHA-1 support.

2021-04-28 22:50 UTC, graebm commented on source/crc32.c
> +    return aws_byte_buf_write_be32(output, crc) ? AWS_OP_SUCCESS : AWS_OP_ERR;
tweak comment, we know that big-endian is needed
`/* Write out bytes in big endian order */`

2021-05-03 15:11 UTC, ilevyor commented on include/aws/s3/s3_streaming_checksum.h
> +struct aws_checksum *aws_checksum_sha256_new(struct aws_allocator *allocator);
@justinboswell

2021-12-09 21:49 UTC, closed without merging